// A1 English Vocabulary - Бүх 32 сэдэв, 520+ үг
const VOCAB_DATA = [
  // 1. Hello and Goodbye
  { w: "Hello", c: "Hello and Goodbye", ipa: "/hɛˈloʊ/", mn: "хэлө́ү", tr: "Сайн байна уу?" },
  { w: "Goodbye", c: "Hello and Goodbye", ipa: "/ɡʊdˈbaɪ/", mn: "гүдба́й", tr: "Баяртай" },
  { w: "Hi", c: "Hello and Goodbye", ipa: "/haɪ/", mn: "хай", tr: "Сайн уу? (энгийн)" },
  { w: "Bye", c: "Hello and Goodbye", ipa: "/baɪ/", mn: "бай", tr: "Баяртай (товч)" },
  { w: "Good morning", c: "Hello and Goodbye", ipa: "/ɡʊd ˈmɔːrnɪŋ/", mn: "гүд мо́орнин", tr: "Өглөөний мэнд" },
  { w: "Good afternoon", c: "Hello and Goodbye", ipa: "/ɡʊd ˌæftərˈnuːn/", mn: "гүд афтану́ун", tr: "Өдрийн мэнд" },
  { w: "Good evening", c: "Hello and Goodbye", ipa: "/ɡʊd ˈiːvnɪŋ/", mn: "гүд и́йвнин", tr: "Оройн мэнд" },
  { w: "Good night", c: "Hello and Goodbye", ipa: "/ɡʊd ˈnaɪt/", mn: "гүд на́йт", tr: "Сайхан амраарай" },
  { w: "Thank you", c: "Hello and Goodbye", ipa: "/ˈθæŋk juː/", mn: "сэнк юү", tr: "Танд баярлалаа" },
  { w: "Thanks", c: "Hello and Goodbye", ipa: "/θæŋks/", mn: "сэнкс", tr: "Баярлалаа (энгийн)" },
  { w: "Please", c: "Hello and Goodbye", ipa: "/pliːz/", mn: "плийз", tr: "Тэгнэ үү / Гуйж байна" },
  { w: "OK", c: "Hello and Goodbye", ipa: "/oʊˈkeɪ/", mn: "оүке́й", tr: "За / Болно" },
  { w: "Yes", c: "Hello and Goodbye", ipa: "/jɛs/", mn: "ес", tr: "Тийм" },
  { w: "No", c: "Hello and Goodbye", ipa: "/noʊ/", mn: "нө́ү", tr: "Үгүй" },
  { w: "Sorry", c: "Hello and Goodbye", ipa: "/ˈsɑːri/", mn: "со́ри", tr: "Уучлаарай" },
  { w: "Welcome", c: "Hello and Goodbye", ipa: "/ˈwɛlkəm/", mn: "вэ́лкэм", tr: "Тавтай морил" },

  // 2. People
  { w: "Man", c: "People", ipa: "/mæn/", mn: "мэн", tr: "Эрэгтэй хүн" },
  { w: "Woman", c: "People", ipa: "/ˈwʊmən/", mn: "вү́мэн", tr: "Эмэгтэй хүн" },
  { w: "Boy", c: "People", ipa: "/bɔɪ/", mn: "бой", tr: "Хүү" },
  { w: "Girl", c: "People", ipa: "/ɡɜːrl/", mn: "гөөл", tr: "Охин" },
  { w: "Friend", c: "People", ipa: "/frɛnd/", mn: "фрэнд", tr: "Найз" },
  { w: "Boyfriend", c: "People", ipa: "/ˈbɔɪfrɛnd/", mn: "бо́йфрэнд", tr: "Найз залуу" },
  { w: "Girlfriend", c: "People", ipa: "/ˈɡɜːrlfrɛnd/", mn: "гөө́лфрэнд", tr: "Найз охин" },
  { w: "Person", c: "People", ipa: "/ˈpɜːrsən/", mn: "пө́өрсон", tr: "Хүн (ганц тоо)" },
  { w: "People", c: "People", ipa: "/ˈpiːpəl/", mn: "пи́йпл", tr: "Хүмүүс (олон тоо)" },
  { w: "Adult", c: "People", ipa: "/əˈdʌlt/", mn: "эда́лт", tr: "Насанд хүрсэн хүн" },
  { w: "Baby", c: "People", ipa: "/ˈbeɪbi/", mn: "бе́йби", tr: "Нярай, нялх хүүхэд" },
  { w: "Mr", c: "People", ipa: "/ˈmɪstər/", mn: "ми́стэр", tr: "Ноён" },
  { w: "Mrs", c: "People", ipa: "/ˈmɪsɪz/", mn: "ми́сиз", tr: "Хатагтай (гэрлэсэн)" },
  { w: "Miss", c: "People", ipa: "/mɪs/", mn: "мис", tr: "Хатагтай (гэрлээгүй)" },

  // 3. Numbers 0 to 100
  { w: "Zero", c: "Numbers", ipa: "/ˈzɪroʊ/", mn: "зи́роу", tr: "Тэг (0)" },
  { w: "One", c: "Numbers", ipa: "/wʌn/", mn: "ван", tr: "Нэг (1)" },
  { w: "Two", c: "Numbers", ipa: "/tuː/", mn: "түү", tr: "Хоёр (2)" },
  { w: "Three", c: "Numbers", ipa: "/θriː/", mn: "срий", tr: "Гурав (3)" },
  { w: "Four", c: "Numbers", ipa: "/fɔːr/", mn: "фоор", tr: "Дөрөв (4)" },
  { w: "Five", c: "Numbers", ipa: "/faɪv/", mn: "файв", tr: "Тав (5)" },
  { w: "Six", c: "Numbers", ipa: "/sɪks/", mn: "сикс", tr: "Зургаа (6)" },
  { w: "Seven", c: "Numbers", ipa: "/ˈsɛvən/", mn: "сэ́вэн", tr: "Долоо (7)" },
  { w: "Eight", c: "Numbers", ipa: "/eɪt/", mn: "эйт", tr: "Найм (8)" },
  { w: "Nine", c: "Numbers", ipa: "/naɪn/", mn: "найн", tr: "Ес (9)" },
  { w: "Ten", c: "Numbers", ipa: "/tɛn/", mn: "тэн", tr: "Арав (10)" },
  { w: "Eleven", c: "Numbers", ipa: "/ɪˈlɛvən/", mn: "илэ́вэн", tr: "Арван нэг (11)" },
  { w: "Twelve", c: "Numbers", ipa: "/twɛlv/", mn: "твэлв", tr: "Арван хоёр (12)" },
  { w: "Thirteen", c: "Numbers", ipa: "/ˌθɜːrˈtiːn/", mn: "сөөрти́йн", tr: "Арван гурав (13)" },
  { w: "Fourteen", c: "Numbers", ipa: "/ˌfɔːrˈtiːn/", mn: "фоорти́йн", tr: "Арван дөрөв (14)" },
  { w: "Fifteen", c: "Numbers", ipa: "/ˌfɪfˈtiːn/", mn: "фифти́йн", tr: "Арван тав (15)" },
  { w: "Sixteen", c: "Numbers", ipa: "/ˌsɪksˈtiːn/", mn: "сиксти́йн", tr: "Арван зургаа (16)" },
  { w: "Seventeen", c: "Numbers", ipa: "/ˌsɛvənˈtiːn/", mn: "сэвэнти́йн", tr: "Арван долоо (17)" },
  { w: "Eighteen", c: "Numbers", ipa: "/ˌeɪˈtiːn/", mn: "эйти́йн", tr: "Арван найм (18)" },
  { w: "Nineteen", c: "Numbers", ipa: "/ˌnaɪnˈtiːn/", mn: "найнти́йн", tr: "Арван ес (19)" },
  { w: "Twenty", c: "Numbers", ipa: "/ˈtwɛnti/", mn: "твэ́нти", tr: "Хорь (20)" },
  { w: "Thirty", c: "Numbers", ipa: "/ˈθɜːrti/", mn: "сөө́рти", tr: "Гуч (30)" },
  { w: "Forty", c: "Numbers", ipa: "/ˈfɔːrti/", mn: "фо́орти", tr: "Дөч (40)" },
  { w: "Fifty", c: "Numbers", ipa: "/ˈfɪfti/", mn: "фи́фти", tr: "Тавь (50)" },
  { w: "Sixty", c: "Numbers", ipa: "/ˈsɪksti/", mn: "си́ксти", tr: "Жар (60)" },
  { w: "Seventy", c: "Numbers", ipa: "/ˈsɛvənti/", mn: "сэ́вэнти", tr: "Дал (70)" },
  { w: "Eighty", c: "Numbers", ipa: "/ˈeɪti/", mn: "э́йти", tr: "Ная (80)" },
  { w: "Ninety", c: "Numbers", ipa: "/ˈnaɪnti/", mn: "на́йнти", tr: "Ер (90)" },
  { w: "Hundred", c: "Numbers", ipa: "/ˈhʌndrəd/", mn: "ха́ндрэд", tr: "Зуу (100)" },

  // 4. Family
  { w: "Parent", c: "Family", ipa: "/ˈpɛrənt/", mn: "пэ́рэнт", tr: "Эцэг эх" },
  { w: "Father", c: "Family", ipa: "/ˈfɑːðər/", mn: "фа́адэр", tr: "Аав, эцэг" },
  { w: "Mother", c: "Family", ipa: "/ˈmʌðər/", mn: "ма́дэр", tr: "Ээж, эх" },
  { w: "Dad", c: "Family", ipa: "/dæd/", mn: "дэд", tr: "Аав (энгийн)" },
  { w: "Mom", c: "Family", ipa: "/mɑːm/", mn: "мам", tr: "Ээж (энгийн)" },
  { w: "Wife", c: "Family", ipa: "/waɪf/", mn: "вайф", tr: "Эхнэр" },
  { w: "Husband", c: "Family", ipa: "/ˈhʌzbənd/", mn: "ха́збэнд", tr: "Нөхөр" },
  { w: "Child", c: "Family", ipa: "/tʃaɪld/", mn: "чайлд", tr: "Хүүхэд (ганц тоо)" },
  { w: "Son", c: "Family", ipa: "/sʌn/", mn: "сан", tr: "Хүү" },
  { w: "Daughter", c: "Family", ipa: "/ˈdɔːtər/", mn: "до́отэр", tr: "Охин" },
  { w: "Sister", c: "Family", ipa: "/ˈsɪstər/", mn: "си́стэр", tr: "Эгч, эмэгтэй дүү" },
  { w: "Brother", c: "Family", ipa: "/ˈbrʌðər/", mn: "бра́дэр", tr: "Ах, эрэгтэй дүү" },
  { w: "Family", c: "Family", ipa: "/ˈfæməli/", mn: "фэ́мэли", tr: "Гэр бүл" },
  { w: "Grandmother", c: "Family", ipa: "/ˈɡrænˌmʌðər/", mn: "грэ́нмадэр", tr: "Эмээ" },
  { w: "Grandfather", c: "Family", ipa: "/ˈɡrænˌfɑːðər/", mn: "грэ́нфаадэр", tr: "Өвөө" },
  { w: "Grandchild", c: "Family", ipa: "/ˈɡrænˌtʃaɪld/", mn: "грэ́нчайлд", tr: "Ач, зээ хүүхэд" },
  { w: "Aunt", c: "Family", ipa: "/ænt/", mn: "энт", tr: "Авга эгч, нагац эгч" },
  { w: "Uncle", c: "Family", ipa: "/ˈʌŋkəl/", mn: "а́нкл", tr: "Авга ах, нагац ах" },
  { w: "Niece", c: "Family", ipa: "/niːs/", mn: "нийс", tr: "Үеэл охин, ач/зээ охин" },
  { w: "Nephew", c: "Family", ipa: "/ˈnɛfjuː/", mn: "нэ́фью", tr: "Үеэл хүү, ач/зээ хүү" },
  { w: "Cousin", c: "Family", ipa: "/ˈkʌzən/", mn: "ка́зн", tr: "Үеэл" },

  // 5. Colors
  { w: "Black", c: "Colors", ipa: "/blæk/", mn: "блэк", tr: "Хар өнгө" },
  { w: "White", c: "Colors", ipa: "/waɪt/", mn: "вайт", tr: "Цагаан өнгө" },
  { w: "Blue", c: "Colors", ipa: "/bluː/", mn: "блүү", tr: "Цэнхэр өнгө" },
  { w: "Green", c: "Colors", ipa: "/ɡriːn/", mn: "грийн", tr: "Ногоон өнгө" },
  { w: "Yellow", c: "Colors", ipa: "/ˈjɛloʊ/", mn: "е́лоу", tr: "Шар өнгө" },
  { w: "Red", c: "Colors", ipa: "/rɛd/", mn: "рэд", tr: "Улаан өнгө" },
  { w: "Pink", c: "Colors", ipa: "/pɪŋk/", mn: "пинк", tr: "Ягаан өнгө" },
  { w: "Orange", c: "Colors", ipa: "/ˈɔːrɪndʒ/", mn: "о́ринж", tr: "Улбар шар өнгө" },
  { w: "Purple", c: "Colors", ipa: "/ˈpɜːrpəl/", mn: "пөө́рпл", tr: "Нил ягаан өнгө" },
  { w: "Gray", c: "Colors", ipa: "/ɡreɪ/", mn: "грэй", tr: "Саарал өнгө" },
  { w: "Brown", c: "Colors", ipa: "/braʊn/", mn: "браун", tr: "Бор өнгө" },
  { w: "Dark", c: "Colors", ipa: "/dɑːrk/", mn: "даарк", tr: "Бараан, тод" },
  { w: "Light", c: "Colors", ipa: "/laɪt/", mn: "лайт", tr: "Гэгээлэг, цайвар" },
  { w: "Color", c: "Colors", ipa: "/ˈkʌlər/", mn: "ка́лэр", tr: "Өнгө" },

  // 6. Months and Seasons
  { w: "Month", c: "Months and Seasons", ipa: "/mʌnθ/", mn: "манс", tr: "Сар (хуанлийн)" },
  { w: "January", c: "Months and Seasons", ipa: "/ˈdʒænjuˌɛri/", mn: "жэ́ньюэри", tr: "1-р сар" },
  { w: "February", c: "Months and Seasons", ipa: "/ˈfɛbruˌɛri/", mn: "фэ́бруэри", tr: "2-р сар" },
  { w: "March", c: "Months and Seasons", ipa: "/mɑːrtʃ/", mn: "маарч", tr: "3-р сар" },
  { w: "April", c: "Months and Seasons", ipa: "/ˈeɪprəl/", mn: "э́йприл", tr: "4-р сар" },
  { w: "May", c: "Months and Seasons", ipa: "/meɪ/", mn: "мэй", tr: "5-р сар" },
  { w: "June", c: "Months and Seasons", ipa: "/dʒuːn/", mn: "жүүн", tr: "6-р сар" },
  { w: "July", c: "Months and Seasons", ipa: "/dʒuˈlaɪ/", mn: "жула́й", tr: "7-р сар" },
  { w: "August", c: "Months and Seasons", ipa: "/ˈɔːɡəst/", mn: "о́огэст", tr: "8-р сар" },
  { w: "September", c: "Months and Seasons", ipa: "/sɛpˈtɛmbər/", mn: "сэптэ́мбэр", tr: "9-р сар" },
  { w: "October", c: "Months and Seasons", ipa: "/ɑːkˈtoʊbər/", mn: "акто́убэр", tr: "10-р сар" },
  { w: "November", c: "Months and Seasons", ipa: "/noʊˈvɛmbər/", mn: "ноувэ́мбэр", tr: "11-р сар" },
  { w: "December", c: "Months and Seasons", ipa: "/dɪˈsɛmbər/", mn: "дисэ́мбэр", tr: "12-р сар" },
  { w: "Season", c: "Months and Seasons", ipa: "/ˈsiːzən/", mn: "си́йзн", tr: "Улирал" },
  { w: "Spring", c: "Months and Seasons", ipa: "/sprɪŋ/", mn: "сприн", tr: "Хавар" },
  { w: "Summer", c: "Months and Seasons", ipa: "/ˈsʌmər/", mn: "са́мэр", tr: "Зун" },
  { w: "Fall", c: "Months and Seasons", ipa: "/fɔːl/", mn: "фоол", tr: "Намар" },
  { w: "Winter", c: "Months and Seasons", ipa: "/ˈwɪntər/", mn: "ви́нтэр", tr: "Өвөл" },

  // 7. Time and Date
  { w: "Clock", c: "Time and Date", ipa: "/klɑːk/", mn: "клак", tr: "Ханын цаг" },
  { w: "Year", c: "Time and Date", ipa: "/jɪr/", mn: "йир", tr: "Жил" },
  { w: "Time", c: "Time and Date", ipa: "/taɪm/", mn: "тайм", tr: "Цаг хугацаа" },
  { w: "Date", c: "Time and Date", ipa: "/deɪt/", mn: "дэйт", tr: "Он сар өдөр" },
  { w: "Day", c: "Time and Date", ipa: "/deɪ/", mn: "дэй", tr: "Өдөр" },
  { w: "Hour", c: "Time and Date", ipa: "/ˈaʊər/", mn: "а́уэр", tr: "Цаг (60 минут)" },
  { w: "O'clock", c: "Time and Date", ipa: "/əˈklɑːk/", mn: "экла́к", tr: "Цаг заах" },
  { w: "Minute", c: "Time and Date", ipa: "/ˈmɪnɪt/", mn: "ми́нит", tr: "Минут" },
  { w: "Second", c: "Time and Date", ipa: "/ˈsɛkənd/", mn: "сэ́кэнд", tr: "Секунд" },
  { w: "Morning", c: "Time and Date", ipa: "/ˈmɔːrnɪŋ/", mn: "мо́орнин", tr: "Өглөө" },
  { w: "Afternoon", c: "Time and Date", ipa: "/ˌæftərˈnuːn/", mn: "афтану́ун", tr: "Өдөр" },
  { w: "Evening", c: "Time and Date", ipa: "/ˈiːvnɪŋ/", mn: "и́йвнин", tr: "Орой" },
  { w: "Night", c: "Time and Date", ipa: "/naɪt/", mn: "найт", tr: "Шөнө" },
  { w: "Week", c: "Time and Date", ipa: "/wiːk/", mn: "вийк", tr: "Долоо хоног" },
  { w: "Sunday", c: "Time and Date", ipa: "/ˈsʌndeɪ/", mn: "са́ндэй", tr: "Ням гараг" },
  { w: "Monday", c: "Time and Date", ipa: "/ˈmʌndeɪ/", mn: "ма́ндэй", tr: "Даваа гараг" },
  { w: "Tuesday", c: "Time and Date", ipa: "/ˈtuːzdeɪ/", mn: "түү́здэй", tr: "Мягмар гараг" },
  { w: "Wednesday", c: "Time and Date", ipa: "/ˈwɛnzdeɪ/", mn: "вэ́нздэй", tr: "Лхагва гараг" },
  { w: "Thursday", c: "Time and Date", ipa: "/ˈθɜːrzdeɪ/", mn: "сөө́рздэй", tr: "Пүрэв гараг" },
  { w: "Friday", c: "Time and Date", ipa: "/ˈfraɪdeɪ/", mn: "фра́йдэй", tr: "Баасан гараг" },
  { w: "Saturday", c: "Time and Date", ipa: "/ˈsætərdeɪ/", mn: "сэ́тэдэй", tr: "Бямба гараг" },
  { w: "Weekend", c: "Time and Date", ipa: "/ˈwiːkˌɛnd/", mn: "ви́йкэнд", tr: "Амралтын өдрүүд" },
  { w: "Next", c: "Time and Date", ipa: "/nɛkst/", mn: "нэкст", tr: "Дараагийн" },
  { w: "Half", c: "Time and Date", ipa: "/hæf/", mn: "хэф", tr: "Хагас, тал" },

  // 8. Personal Information
  { w: "Name", c: "Personal Information", ipa: "/neɪm/", mn: "нэйм", tr: "Нэр" },
  { w: "Last name", c: "Personal Information", ipa: "/læst neɪm/", mn: "лэст нэйм", tr: "Овог" },
  { w: "Age", c: "Personal Information", ipa: "/eɪdʒ/", mn: "эйж", tr: "Нас" },
  { w: "Address", c: "Personal Information", ipa: "/ˈædrɛs/", mn: "э́дрэс", tr: "Гэрийн хаяг" },
  { w: "Birthday", c: "Personal Information", ipa: "/ˈbɜːrθdeɪ/", mn: "бөө́рсдэй", tr: "Төрсөн өдөр" },
  { w: "Birthdate", c: "Personal Information", ipa: "/ˈbɜːrθdeɪt/", mn: "бөө́рсдэйт", tr: "Төрсөн он сар өдөр" },
  { w: "Single", c: "Personal Information", ipa: "/ˈsɪŋɡəl/", mn: "си́нгл", tr: "Ганц бие" },
  { w: "Married", c: "Personal Information", ipa: "/ˈmærid/", mn: "мэ́рид", tr: "Гэрлэсэн" },
  { w: "Passport", c: "Personal Information", ipa: "/ˈpæspɔːrt/", mn: "пэ́споорт", tr: "Гадаад паспорт" },
  { w: "Phone number", c: "Personal Information", ipa: "/foʊn ˈnʌmbər/", mn: "фоун на́мбэр", tr: "Утасны дугаар" },
  { w: "Question", c: "Personal Information", ipa: "/ˈkwɛstʃən/", mn: "квэ́счэн", tr: "Асуулт" },
  { w: "Answer", c: "Personal Information", ipa: "/ˈænsər/", mn: "э́нсэр", tr: "Хариулт" },

  // 9. The Body
  { w: "Body", c: "The Body", ipa: "/ˈbɑːdi/", mn: "ба́ди", tr: "Хүний бие" },
  { w: "Hand", c: "The Body", ipa: "/hænd/", mn: "хэнд", tr: "Гар (сарвуу)" },
  { w: "Arm", c: "The Body", ipa: "/ɑːrm/", mn: "аарм", tr: "Гар (бүхэлдээ)" },
  { w: "Foot", c: "The Body", ipa: "/fʊt/", mn: "фүт", tr: "Хөл (тавхай)" },
  { w: "Head", c: "The Body", ipa: "/hɛd/", mn: "хэд", tr: "Толгой" },
  { w: "Leg", c: "The Body", ipa: "/lɛɡ/", mn: "лэг", tr: "Хөл" },
  { w: "Knee", c: "The Body", ipa: "/niː/", mn: "ний", tr: "Өвдөг" },
  { w: "Back", c: "The Body", ipa: "/bæk/", mn: "бэк", tr: "Нуруу, ар тал" },
  { w: "Stomach", c: "The Body", ipa: "/ˈstʌmək/", mn: "ста́мэк", tr: "Ходоод, гэдэс" },

  // 10. The Head and Face
  { w: "Hair", c: "The Head and Face", ipa: "/hɛr/", mn: "хээр", tr: "Үс" },
  { w: "Neck", c: "The Head and Face", ipa: "/nɛk/", mn: "нэк", tr: "Хүзүү" },
  { w: "Face", c: "The Head and Face", ipa: "/feɪs/", mn: "фэйс", tr: "Нүүр царай" },
  { w: "Eye", c: "The Head and Face", ipa: "/aɪ/", mn: "ай", tr: "Нүд" },
  { w: "Nose", c: "The Head and Face", ipa: "/noʊz/", mn: "нөүз", tr: "Хамар" },
  { w: "Ear", c: "The Head and Face", ipa: "/ɪr/", mn: "ир", tr: "Чих" },
  { w: "Cheek", c: "The Head and Face", ipa: "/tʃiːk/", mn: "чийк", tr: "Хацар" },
  { w: "Chin", c: "The Head and Face", ipa: "/tʃɪn/", mn: "чин", tr: "Эрүү" },
  { w: "Mouth", c: "The Head and Face", ipa: "/maʊθ/", mn: "маус", tr: "Ам" },
  { w: "Tooth", c: "The Head and Face", ipa: "/tuːθ/", mn: "түүс", tr: "Шүд" },
  { w: "Lip", c: "The Head and Face", ipa: "/lɪp/", mn: "лип", tr: "Уруул" },

  // 11. Opposite Adjectives
  { w: "Good", c: "Opposite Adjectives", ipa: "/ɡʊd/", mn: "гүд", tr: "Сайн" },
  { w: "Bad", c: "Opposite Adjectives", ipa: "/bæd/", mn: "бэд", tr: "Муу" },
  { w: "High", c: "Opposite Adjectives", ipa: "/haɪ/", mn: "хай", tr: "Өндөр" },
  { w: "Low", c: "Opposite Adjectives", ipa: "/loʊ/", mn: "лоу", tr: "Намхан, доор" },
  { w: "Big", c: "Opposite Adjectives", ipa: "/bɪɡ/", mn: "биг", tr: "Том" },
  { w: "Small", c: "Opposite Adjectives", ipa: "/smɔːl/", mn: "смоол", tr: "Жижиг" },
  { w: "Heavy", c: "Opposite Adjectives", ipa: "/ˈhɛvi/", mn: "хэ́ви", tr: "Хүнд (жин)" },
  { w: "Light", c: "Opposite Adjectives", ipa: "/laɪt/", mn: "лайт", tr: "Хөнгөн" },
  { w: "Expensive", c: "Opposite Adjectives", ipa: "/ɪkˈspɛnsɪv/", mn: "экспэ́нсив", tr: "Үнэтэй" },
  { w: "Cheap", c: "Opposite Adjectives", ipa: "/tʃiːp/", mn: "чийп", tr: "Хямдхан" },
  { w: "Old", c: "Opposite Adjectives", ipa: "/oʊld/", mn: "оулд", tr: "Хуучин, хөгшин" },
  { w: "New", c: "Opposite Adjectives", ipa: "/nuː/", mn: "нүү", tr: "Шинэ" },
  { w: "Beautiful", c: "Opposite Adjectives", ipa: "/ˈbjuːtɪfəl/", mn: "бью́тифул", tr: "Үзэсгэлэнтэй" },
  { w: "Ugly", c: "Opposite Adjectives", ipa: "/ˈʌɡli/", mn: "а́гли", tr: "Цухал, муухай" },
  { w: "Clean", c: "Opposite Adjectives", ipa: "/kliːn/", mn: "клийн", tr: "Цэвэрхэн" },
  { w: "Dirty", c: "Opposite Adjectives", ipa: "/ˈdɜːrti/", mn: "дөө́рти", tr: "Бохир" },
  { w: "Easy", c: "Opposite Adjectives", ipa: "/ˈiːzi/", mn: "и́йзи", tr: "Амархан" },
  { w: "Difficult", c: "Opposite Adjectives", ipa: "/ˈdɪfɪkəlt/", mn: "ди́фикөлт", tr: "Хэцүү" },
  { w: "Fast", c: "Opposite Adjectives", ipa: "/fæst/", mn: "фэст", tr: "Хурдан" },
  { w: "Slow", c: "Opposite Adjectives", ipa: "/sloʊ/", mn: "слоу", tr: "Удаан" },
  { w: "Different", c: "Opposite Adjectives", ipa: "/ˈdɪfərənt/", mn: "ди́фрэнт", tr: "Өөр, ялгаатай" },
  { w: "Same", c: "Opposite Adjectives", ipa: "/seɪm/", mn: "сэйм", tr: "Ижил, адилхан" },
  { w: "Right", c: "Opposite Adjectives", ipa: "/raɪt/", mn: "райт", tr: "Зөв" },
  { w: "Wrong", c: "Opposite Adjectives", ipa: "/rɔːŋ/", mn: "роон", tr: "Буруу" },
  { w: "Open", c: "Opposite Adjectives", ipa: "/ˈoʊpən/", mn: "о́упэн", tr: "Нээлттэй" },
  { w: "Closed", c: "Opposite Adjectives", ipa: "/kloʊzd/", mn: "клоузд", tr: "Хаалттай" },
  { w: "True", c: "Opposite Adjectives", ipa: "/truː/", mn: "трүү", tr: "Үнэн" },
  { w: "False", c: "Opposite Adjectives", ipa: "/fɔːls/", mn: "фоолс", tr: "Худал" },
  { w: "Rich", c: "Opposite Adjectives", ipa: "/rɪtʃ/", mn: "рич", tr: "Баян" },
  { w: "Poor", c: "Opposite Adjectives", ipa: "/pʊr/", mn: "пүүр", tr: "Ядуу" },
  { w: "Sure", c: "Opposite Adjectives", ipa: "/ʃʊr/", mn: "шүүр", tr: "Итгэлтэй" },
  { w: "Unsure", c: "Opposite Adjectives", ipa: "/ʌnˈʃʊr/", mn: "аншүү́р", tr: "Эргэлзээтэй" },
  { w: "Correct", c: "Opposite Adjectives", ipa: "/kəˈrɛkt/", mn: "кэрэ́кт", tr: "Зөв, алдаагүй" },
  { w: "Incorrect", c: "Opposite Adjectives", ipa: "/ˌɪnkəˈrɛkt/", mn: "инкэрэ́кт", tr: "Буруу, алдаатай" },

  // 12. House and Apartment
  { w: "Building", c: "House and Apartment", ipa: "/ˈbɪldɪŋ/", mn: "би́лдин", tr: "Барилга" },
  { w: "House", c: "House and Apartment", ipa: "/haʊs/", mn: "хаус", tr: "Хувийн байшин" },
  { w: "Home", c: "House and Apartment", ipa: "/hoʊm/", mn: "хоум", tr: "Гэр" },
  { w: "Apartment", c: "House and Apartment", ipa: "/əˈpɑːrtmənt/", mn: "эпа́артмэнт", tr: "Орон сууц" },
  { w: "Floor", c: "House and Apartment", ipa: "/flɔːr/", mn: "флоор", tr: "Шал, давхар" },
  { w: "Door", c: "House and Apartment", ipa: "/dɔːr/", mn: "доор", tr: "Хаалга" },
  { w: "Window", c: "House and Apartment", ipa: "/ˈwɪndoʊ/", mn: "ви́ндоу", tr: "Цонх" },
  { w: "Wall", c: "House and Apartment", ipa: "/wɔːl/", mn: "воол", tr: "Хана" },
  { w: "Room", c: "House and Apartment", ipa: "/ruːm/", mn: "рүүм", tr: "Өрөө" },
  { w: "Roof", c: "House and Apartment", ipa: "/ruːf/", mn: "рүүф", tr: "Дээвэр" },
  { w: "Ceiling", c: "House and Apartment", ipa: "/ˈsiːlɪŋ/", mn: "си́йлин", tr: "Тааз" },
  { w: "Living room", c: "House and Apartment", ipa: "/ˈlɪvɪŋ ruːm/", mn: "ли́вин рүүм", tr: "Зочны өрөө" },
  { w: "Dining room", c: "House and Apartment", ipa: "/ˈdaɪnɪŋ ruːm/", mn: "да́йнин рүүм", tr: "Хоолны өрөө" },
  { w: "Kitchen", c: "House and Apartment", ipa: "/ˈkɪtʃɪn/", mn: "ки́чин", tr: "Гал тогооны өрөө" },
  { w: "Bedroom", c: "House and Apartment", ipa: "/ˈbɛdruːm/", mn: "бэ́дрүүм", tr: "Унтлагын өрөө" },
  { w: "Bathroom", c: "House and Apartment", ipa: "/ˈbæθruːm/", mn: "бэ́срүүм", tr: "Угаалгын өрөө" },
  { w: "Garden", c: "House and Apartment", ipa: "/ˈɡɑːrdən/", mn: "гаа́рдэн", tr: "Цэцэрлэгт талбай" },
  { w: "Upstairs", c: "House and Apartment", ipa: "/ˌʌpˈstɛrz/", mn: "апстэ́эрз", tr: "Дээд давхарт" },
  { w: "Downstairs", c: "House and Apartment", ipa: "/ˌdaʊnˈstɛrz/", mn: "даунстэ́эрз", tr: "Доод давхарт" },
  { w: "Closet", c: "House and Apartment", ipa: "/ˈklɑːzɪt/", mn: "кла́зит", tr: "Хувцасны шүүгээ" },
  { w: "Part", c: "House and Apartment", ipa: "/pɑːrt/", mn: "паарт", tr: "Хэсэг" },
  { w: "Elevator", c: "House and Apartment", ipa: "/ˈɛləˌveɪtər/", mn: "э́лэвэйтэр", tr: "Цахилгаан шат" },
  { w: "Yard", c: "House and Apartment", ipa: "/jɑːrd/", mn: "яард", tr: "Хашаа, талбай" },

  // 13. Furniture and Home Appliances
  { w: "Desk", c: "Furniture", ipa: "/dɛsk/", mn: "дэск", tr: "Бичгийн ширээ" },
  { w: "Chair", c: "Furniture", ipa: "/tʃɛr/", mn: "чээр", tr: "Сандал" },
  { w: "Table", c: "Furniture", ipa: "/ˈteɪbəl/", mn: "тэ́йбл", tr: "Ширээ" },
  { w: "Sofa", c: "Furniture", ipa: "/ˈsoʊfə/", mn: "со́уфа", tr: "Буйдан" },
  { w: "Bed", c: "Furniture", ipa: "/bɛd/", mn: "бэд", tr: "Ор" },
  { w: "Cabinet", c: "Furniture", ipa: "/ˈkæbɪnɪt/", mn: "кэ́бинит", tr: "Шүүгээ" },
  { w: "Fridge", c: "Furniture", ipa: "/frɪdʒ/", mn: "фриж", tr: "Хөргөгч" },
  { w: "TV", c: "Furniture", ipa: "/ˌtiːˈviː/", mn: "ти́йвий", tr: "Зурагт" },
  { w: "Stove", c: "Furniture", ipa: "/stoʊv/", mn: "стоув", tr: "Плитка, зуух" },

  // 14. Jobs
  { w: "Money", c: "Jobs", ipa: "/ˈmʌni/", mn: "ма́ни", tr: "Мөнгө" },
  { w: "Job", c: "Jobs", ipa: "/dʒɑːb/", mn: "жааб", tr: "Ажил" },
  { w: "Work", c: "Jobs", ipa: "/wɜːrk/", mn: "вөөөрк", tr: "Ажил хөдөлмөр" },
  { w: "Doctor", c: "Jobs", ipa: "/ˈdɑːktər/", mn: "да́ктэр", tr: "Эмч" },
  { w: "Dentist", c: "Jobs", ipa: "/ˈdɛntɪst/", mn: "дэ́нтист", tr: "Шүдний эмч" },
  { w: "Nurse", c: "Jobs", ipa: "/nɜːrs/", mn: "нөөрс", tr: "Сувилагч" },
  { w: "Teacher", c: "Jobs", ipa: "/ˈtiːtʃər/", mn: "ти́йчэр", tr: "Багш" },
  { w: "Engineer", c: "Jobs", ipa: "/ˌɛndʒɪˈnɪr/", mn: "энжини́р", tr: "Инженер" },
  { w: "Actor", c: "Jobs", ipa: "/ˈæktər/", mn: "э́ктэр", tr: "Эрэгтэй жүжигчин" },
  { w: "Actress", c: "Jobs", ipa: "/ˈæktrɪs/", mn: "э́ктрис", tr: "Эмэгтэй жүжигчин" },
  { w: "Police officer", c: "Jobs", ipa: "/pəˈliːs ˈɔːfɪsər/", mn: "пэли́йс о́фисэр", tr: "Цагдаа" },
  { w: "Waiter", c: "Jobs", ipa: "/ˈweɪtər/", mn: "вэ́йтэр", tr: "Эрэгтэй зөөгч" },
  { w: "Waitress", c: "Jobs", ipa: "/ˈweɪtrɪs/", mn: "вэ́йтрис", tr: "Эмэгтэй зөөгч" },
  { w: "Driver", c: "Jobs", ipa: "/ˈdraɪvər/", mn: "дра́йвэр", tr: "Жолооч" },

  // 15. Clothes and Shoes
  { w: "Clothes", c: "Clothes and Shoes", ipa: "/kloʊðz/", mn: "клоуз", tr: "Хувцас" },
  { w: "Shirt", c: "Clothes and Shoes", ipa: "/ʃɜːrt/", mn: "шөөрт", tr: "Цамц (захтай)" },
  { w: "T-shirt", c: "Clothes and Shoes", ipa: "/ˈtiːˌʃɜːrt/", mn: "ти́й шөөрт", tr: "Футболк" },
  { w: "Pants", c: "Clothes and Shoes", ipa: "/pænts/", mn: "пэнтс", tr: "Өмд" },
  { w: "Dress", c: "Clothes and Shoes", ipa: "/drɛs/", mn: "дрэс", tr: "Даашинз" },
  { w: "Skirt", c: "Clothes and Shoes", ipa: "/skɜːrt/", mn: "скөөрт", tr: "Юбка" },
  { w: "Coat", c: "Clothes and Shoes", ipa: "/koʊt/", mn: "коут", tr: "Пальто" },
  { w: "Jacket", c: "Clothes and Shoes", ipa: "/ˈdʒækɪt/", mn: "жэ́кит", tr: "Хүрэм" },
  { w: "Jeans", c: "Clothes and Shoes", ipa: "/dʒiːnz/", mn: "жийнз", tr: "Жинсэн өмд" },
  { w: "Sweater", c: "Clothes and Shoes", ipa: "/ˈswɛtər/", mn: "свэ́тэр", tr: "Свитер цамц" },
  { w: "Suit", c: "Clothes and Shoes", ipa: "/suːt/", mn: "сүүт", tr: "Хослол" },
  { w: "Tie", c: "Clothes and Shoes", ipa: "/taɪ/", mn: "тай", tr: "Зангиа" },
  { w: "Hat", c: "Clothes and Shoes", ipa: "/hæt/", mn: "хэт", tr: "Малгай" },
  { w: "Purse", c: "Clothes and Shoes", ipa: "/pɜːrs/", mn: "пөөрс", tr: "Гар цүнх" },
  { w: "Shoe", c: "Clothes and Shoes", ipa: "/ʃuː/", mn: "шүү", tr: "Гутал" },
  { w: "Boot", c: "Clothes and Shoes", ipa: "/buːt/", mn: "бүүт", tr: "Ботинк, гутал" },
  { w: "Sock", c: "Clothes and Shoes", ipa: "/sɑːk/", mn: "сак", tr: "Оймс" },
  { w: "Pajamas", c: "Clothes and Shoes", ipa: "/pəˈdʒæməz/", mn: "пэжа́маз", tr: "Унтлагын хувцас" },
  { w: "Underwear", c: "Clothes and Shoes", ipa: "/ˈʌndərˌwɛr/", mn: "а́ндэрвээр", tr: "Дотуур хувцас" },
  { w: "Swimsuit", c: "Clothes and Shoes", ipa: "/ˈswɪmˌsuːt/", mn: "сви́мсүүт", tr: "Усны хувцас" },

  // 16. Animals
  { w: "Animal", c: "Animals", ipa: "/ˈænəməl/", mn: "э́нимэл", tr: "Амьтан" },
  { w: "Cat", c: "Animals", ipa: "/kæt/", mn: "кэт", tr: "Муур" },
  { w: "Dog", c: "Animals", ipa: "/dɔːɡ/", mn: "доог", tr: "Нохой" },
  { w: "Horse", c: "Animals", ipa: "/hɔːrs/", mn: "хоорс", tr: "Морь" },
  { w: "Sheep", c: "Animals", ipa: "/ʃiːp/", mn: "шийп", tr: "Хонь" },
  { w: "Cow", c: "Animals", ipa: "/kaʊ/", mn: "кау", tr: "Үхэр" },
  { w: "Pig", c: "Animals", ipa: "/pɪɡ/", mn: "пиг", tr: "Гахай" },
  { w: "Lion", c: "Animals", ipa: "/ˈlaɪən/", mn: "ла́йэн", tr: "Арслан" },
  { w: "Rabbit", c: "Animals", ipa: "/ˈræbɪt/", mn: "рэ́бит", tr: "Туулай" },
  { w: "Mouse", c: "Animals", ipa: "/maʊs/", mn: "маус", tr: "Хулгана" },
  { w: "Snake", c: "Animals", ipa: "/sneɪk/", mn: "снэйк", tr: "Могой" },
  { w: "Fish", c: "Animals", ipa: "/fɪʃ/", mn: "фиш", tr: "Загас" },
  { w: "Elephant", c: "Animals", ipa: "/ˈɛləfənt/", mn: "э́лифэнт", tr: "Заан" },
  { w: "Bird", c: "Animals", ipa: "/bɜːrd/", mn: "бөөрд", tr: "Шувуу" },
  { w: "Chicken", c: "Animals", ipa: "/ˈtʃɪkɪn/", mn: "чи́кин", tr: "Тахиа" },

  // 17. Basic Verbs
  { w: "Be", c: "Basic Verbs", ipa: "/biː/", mn: "бий", tr: "Байх, орших" },
  { w: "Wake up", c: "Basic Verbs", ipa: "/weɪk ʌp/", mn: "вэйк ап", tr: "Сэрэх" },
  { w: "Sleep", c: "Basic Verbs", ipa: "/sliːp/", mn: "слийп", tr: "Унтах" },
  { w: "Work", c: "Basic Verbs", ipa: "/wɜːrk/", mn: "вөөөрк", tr: "Ажиллах" },
  { w: "Drive", c: "Basic Verbs", ipa: "/draɪv/", mn: "драйв", tr: "Жолоодох" },
  { w: "Buy", c: "Basic Verbs", ipa: "/baɪ/", mn: "бай", tr: "Худалдаж авах" },
  { w: "Sell", c: "Basic Verbs", ipa: "/sɛl/", mn: "сэл", tr: "Зарах" },
  { w: "Read", c: "Basic Verbs", ipa: "/riːd/", mn: "рийд", tr: "Унших" },
  { w: "Write", c: "Basic Verbs", ipa: "/raɪt/", mn: "райт", tr: "Бичих" },
  { w: "Play", c: "Basic Verbs", ipa: "/pleɪ/", mn: "плэй", tr: "Тоглох" },
  { w: "Pay", c: "Basic Verbs", ipa: "/peɪ/", mn: "пэй", tr: "Төлөх" },
  { w: "Rest", c: "Basic Verbs", ipa: "/rɛst/", mn: "рэст", tr: "Амрах" },
  { w: "Wash", c: "Basic Verbs", ipa: "/wɑːʃ/", mn: "вааш", tr: "Угаах" },
  { w: "Drink", c: "Basic Verbs", ipa: "/drɪŋk/", mn: "дринк", tr: "Уух" },
  { w: "Cook", c: "Basic Verbs", ipa: "/kʊk/", mn: "күк", tr: "Хоол хийх" },
  { w: "Eat", c: "Basic Verbs", ipa: "/iːt/", mn: "ийт", tr: "Идэх" },
  { w: "Have", c: "Basic Verbs", ipa: "/hæv/", mn: "хэв", tr: "Эзэмших, идэх/уух" },
  { w: "Make", c: "Basic Verbs", ipa: "/meɪk/", mn: "мэйк", tr: "Хийх, бүтээх" },
  { w: "Wear", c: "Basic Verbs", ipa: "/wɛr/", mn: "вээр", tr: "Өмсөх" },
  { w: "Clean", c: "Basic Verbs", ipa: "/kliːn/", mn: "клийн", tr: "Цэвэрлэх" },
  { w: "Think", c: "Basic Verbs", ipa: "/θɪŋk/", mn: "синк", tr: "Бодох" },
  { w: "Take", c: "Basic Verbs", ipa: "/teɪk/", mn: "тэйк", tr: "Авах" },
  { w: "Stand", c: "Basic Verbs", ipa: "/stænd/", mn: "стэнд", tr: "Зогсох" },
  { w: "Speak", c: "Basic Verbs", ipa: "/spiːk/", mn: "спийк", tr: "Ярих" },
  { w: "Spell", c: "Basic Verbs", ipa: "/spɛl/", mn: "спэл", tr: "Үсэглэх" },
  { w: "Dislike", c: "Basic Verbs", ipa: "/dɪsˈlaɪk/", mn: "дисла́йк", tr: "Дургүй байх" },
  { w: "Add", c: "Basic Verbs", ipa: "/æd/", mn: "эд", tr: "Нэмэх" },
  { w: "Call", c: "Basic Verbs", ipa: "/kɔːl/", mn: "коол", tr: "Дуудах, залгах" },
  { w: "Create", c: "Basic Verbs", ipa: "/kriˈeɪt/", mn: "криэ́йт", tr: "Бүтээх" },
  { w: "Cut", c: "Basic Verbs", ipa: "/kʌt/", mn: "кат", tr: "Зүсэх, хайчлах" },

  // 18. Household Items
  { w: "Dish", c: "Household Items", ipa: "/dɪʃ/", mn: "диш", tr: "Таваг сав" },
  { w: "Spoon", c: "Household Items", ipa: "/spuːn/", mn: "спүүн", tr: "Халбага" },
  { w: "Fork", c: "Household Items", ipa: "/fɔːrk/", mn: "фоорк", tr: "Сэрээ" },
  { w: "Knife", c: "Household Items", ipa: "/naɪf/", mn: "найф", tr: "Хутга" },
  { w: "Plate", c: "Household Items", ipa: "/pleɪt/", mn: "плэйт", tr: "Хавтгай таваг" },
  { w: "Glass", c: "Household Items", ipa: "/ɡlæs/", mn: "глэс", tr: "Шилэн аяга" },
  { w: "Bottle", c: "Household Items", ipa: "/ˈbɑːtəl/", mn: "ба́тл", tr: "Шил, лонх" },
  { w: "Cup", c: "Household Items", ipa: "/kʌp/", mn: "кап", tr: "Аяга" },
  { w: "Soap", c: "Household Items", ipa: "/soʊp/", mn: "соуп", tr: "Саван" },
  { w: "Brush", c: "Household Items", ipa: "/brʌʃ/", mn: "браш", tr: "Сойз, багс" },
  { w: "Toothbrush", c: "Household Items", ipa: "/ˈtuːθbrʌʃ/", mn: "түү́сбраш", tr: "Шүдний сойз" },
  { w: "Pillow", c: "Household Items", ipa: "/ˈpɪloʊ/", mn: "пи́лоу", tr: "Дэр" },
  { w: "Trash can", c: "Household Items", ipa: "/træʃ kæn/", mn: "трэ́ш кэн", tr: "Хогийн сав" },
  { w: "Box", c: "Household Items", ipa: "/bɑːks/", mn: "бакс", tr: "Хайрцаг" },
  { w: "Thing", c: "Household Items", ipa: "/θɪŋ/", mn: "син", tr: "Юм, зүйл" },
  { w: "Ball", c: "Household Items", ipa: "/bɔːl/", mn: "боол", tr: "Бөмбөг" },
  { w: "Doll", c: "Household Items", ipa: "/dɑːl/", mn: "дал", tr: "Хүүхэлдэй" },

  // 19. Food and Ingredients
  { w: "Food", c: "Food and Ingredients", ipa: "/fuːd/", mn: "фүүд", tr: "Хоол хүнс" },
  { w: "Meat", c: "Food and Ingredients", ipa: "/miːt/", mn: "мийт", tr: "Мах" },
  { w: "Fish", c: "Food and Ingredients", ipa: "/fɪʃ/", mn: "фиш", tr: "Загасны мах" },
  { w: "Chicken", c: "Food and Ingredients", ipa: "/ˈtʃɪkɪn/", mn: "чи́кин", tr: "Тахианы мах" },
  { w: "Vegetable", c: "Food and Ingredients", ipa: "/ˈvɛdʒtəbəl/", mn: "вэ́жтэбл", tr: "Хүнсний ногоо" },
  { w: "Cucumber", c: "Food and Ingredients", ipa: "/ˈkjuːkʌmbər/", mn: "кью́камбэр", tr: "Өргөст хэмх" },
  { w: "Potato", c: "Food and Ingredients", ipa: "/pəˈteɪtoʊ/", mn: "пэтэ́йтоу", tr: "Төмс" },
  { w: "Onion", c: "Food and Ingredients", ipa: "/ˈʌnjən/", mn: "а́ньен", tr: "Сонгино" },
  { w: "Tomato", c: "Food and Ingredients", ipa: "/təˈmeɪtoʊ/", mn: "тэме́йтоу", tr: "Улаан лооль" },
  { w: "Carrot", c: "Food and Ingredients", ipa: "/ˈkærət/", mn: "кэ́рэт", tr: "Лууван" },
  { w: "Pepper", c: "Food and Ingredients", ipa: "/ˈpɛpər/", mn: "пэ́пэр", tr: "Чинжүү, перец" },
  { w: "Fruit", c: "Food and Ingredients", ipa: "/fruːt/", mn: "фрүүт", tr: "Жимс" },
  { w: "Apple", c: "Food and Ingredients", ipa: "/ˈæpəl/", mn: "э́пл", tr: "Алим" },
  { w: "Orange", c: "Food and Ingredients", ipa: "/ˈɔːrɪndʒ/", mn: "о́ринж", tr: "Жүрж" },
  { w: "Grape", c: "Food and Ingredients", ipa: "/ɡreɪp/", mn: "грэйп", tr: "Усан үзэм" },
  { w: "Banana", c: "Food and Ingredients", ipa: "/bəˈnænə/", mn: "бэнэ́нэ", tr: "Гадил" },
  { w: "Peach", c: "Food and Ingredients", ipa: "/piːtʃ/", mn: "пийч", tr: "Тоор" },
  { w: "Lemon", c: "Food and Ingredients", ipa: "/ˈlɛmən/", mn: "лэ́мэн", tr: "Нимбэг" },
  { w: "Milk", c: "Food and Ingredients", ipa: "/mɪlk/", mn: "милк", tr: "Сүү" },
  { w: "Cheese", c: "Food and Ingredients", ipa: "/tʃiːz/", mn: "чийз", tr: "Бяслаг" },
  { w: "Butter", c: "Food and Ingredients", ipa: "/ˈbʌtər/", mn: "ба́тэр", tr: "Цөцгийн тос" },
  { w: "Egg", c: "Food and Ingredients", ipa: "/ɛɡ/", mn: "эг", tr: "Өндөг" },
  { w: "Cream", c: "Food and Ingredients", ipa: "/kriːm/", mn: "крийм", tr: "Цөцгий" },

  // 20. Food and Drinks
  { w: "Meal", c: "Food and Drinks", ipa: "/miːl/", mn: "мийл", tr: "Хоол" },
  { w: "Breakfast", c: "Food and Drinks", ipa: "/ˈbrɛkfəst/", mn: "брэ́кфэст", tr: "Өглөөний цай" },
  { w: "Lunch", c: "Food and Drinks", ipa: "/lʌntʃ/", mn: "ланч", tr: "Өдрийн хоол" },
  { w: "Dinner", c: "Food and Drinks", ipa: "/ˈdɪnər/", mn: "ди́нэр", tr: "Оройн хоол" },
  { w: "Tea", c: "Food and Drinks", ipa: "/tiː/", mn: "тий", tr: "Цай" },
  { w: "Coffee", c: "Food and Drinks", ipa: "/ˈkɔːfi/", mn: "ко́офи", tr: "Кофе" },
  { w: "Cake", c: "Food and Drinks", ipa: "/keɪk/", mn: "кэйк", tr: "Бялуу" },
  { w: "Cookie", c: "Food and Drinks", ipa: "/ˈkʊki/", mn: "кү́ки", tr: "Жигнэмэг" },
  { w: "Bread", c: "Food and Drinks", ipa: "/brɛd/", mn: "брэд", tr: "Талх" },
  { w: "Honey", c: "Food and Drinks", ipa: "/ˈhʌni/", mn: "ха́ни", tr: "Зөгийн бал" },
  { w: "Jam", c: "Food and Drinks", ipa: "/dʒæm/", mn: "жэм", tr: "Жимсний чанамал" },
  { w: "Juice", c: "Food and Drinks", ipa: "/dʒuːs/", mn: "жүүс", tr: "Жүүс" },
  { w: "Ice cream", c: "Food and Drinks", ipa: "/ˈaɪs kriːm/", mn: "а́йс крийм", tr: "Зайрмаг" },
  { w: "Water", c: "Food and Drinks", ipa: "/ˈwɔːtər/", mn: "во́отэр", tr: "Ус" },
  { w: "Rice", c: "Food and Drinks", ipa: "/raɪs/", mn: "райс", tr: "Цагаан будаа" },
  { w: "Chocolate milk", c: "Food and Drinks", ipa: "/ˈtʃɔːklət mɪlk/", mn: "чо́кләт милк", tr: "Шоколадтай сүү" },
  { w: "Soup", c: "Food and Drinks", ipa: "/suːp/", mn: "сүүп", tr: "Шөл" },
  { w: "Salad", c: "Food and Drinks", ipa: "/ˈsæləd/", mn: "сэ́лэд", tr: "Салат" },
  { w: "Pizza", c: "Food and Drinks", ipa: "/ˈpiːtsə/", mn: "пи́йца", tr: "Пицца" },
  { w: "Sandwich", c: "Food and Drinks", ipa: "/ˈsænwɪtʃ/", mn: "сэ́нвич", tr: "Хавчуургатай талх" },
  { w: "Sugar", c: "Food and Drinks", ipa: "/ˈʃʊɡər/", mn: "шү́гэр", tr: "Элсэн чихэр" },
  { w: "Salt", c: "Food and Drinks", ipa: "/sɔːlt/", mn: "соолт", tr: "Давс" },

  // 21. Describing People
  { w: "Young", c: "Describing People", ipa: "/jʌŋ/", mn: "ян", tr: "Залуу" },
  { w: "Old", c: "Describing People", ipa: "/oʊld/", mn: "оулд", tr: "Хөгшин, настай" },
  { w: "Stupid", c: "Describing People", ipa: "/ˈstuːpɪd/", mn: "стүү́пид", tr: "Тэнэг, мулгуу" },
  { w: "Thirsty", c: "Describing People", ipa: "/ˈθɜːrsti/", mn: "сөө́рсти", tr: "Цангасан" },
  { w: "Fat", c: "Describing People", ipa: "/fæt/", mn: "фэт", tr: "Тарган" },
  { w: "Thin", c: "Describing People", ipa: "/θɪn/", mn: "син", tr: "Туранхай" },
  { w: "Tall", c: "Describing People", ipa: "/tɔːl/", mn: "тоол", tr: "Өндөр" },
  { w: "Smart", c: "Describing People", ipa: "/smɑːrt/", mn: "смаарт", tr: "Ухаантай" },
  { w: "Angry", c: "Describing People", ipa: "/ˈæŋɡri/", mn: "э́нгри", tr: "Ууртай" },
  { w: "Fine", c: "Describing People", ipa: "/faɪn/", mn: "файн", tr: "Зүгээр, сайн" },
  { w: "Sad", c: "Describing People", ipa: "/sæd/", mn: "сэд", tr: "Гунигтай" },
  { w: "Happy", c: "Describing People", ipa: "/ˈhæpi/", mn: "хэ́пи", tr: "Аз жаргалтай" },
  { w: "Hungry", c: "Describing People", ipa: "/ˈhʌŋɡri/", mn: "ха́нгри", tr: "Өлссөн" },
  { w: "Excited", c: "Describing People", ipa: "/ɪkˈsaɪtɪd/", mn: "экса́йтид", tr: "Догдолсон" },
  { w: "Ready", c: "Describing People", ipa: "/ˈrɛdi/", mn: "рэ́ди", tr: "Бэлэн" },

  // 22. The Weather and Nature
  { w: "Weather", c: "Weather and Nature", ipa: "/ˈwɛðər/", mn: "вэ́дэр", tr: "Цаг агаар" },
  { w: "Fire", c: "Weather and Nature", ipa: "/ˈfaɪər/", mn: "фа́йэр", tr: "Гал" },
  { w: "Hot", c: "Weather and Nature", ipa: "/hɑːt/", mn: "хаат", tr: "Халуун" },
  { w: "Cold", c: "Weather and Nature", ipa: "/koʊld/", mn: "коулд", tr: "Хүйтэн" },
  { w: "Sunny", c: "Weather and Nature", ipa: "/ˈsʌni/", mn: "са́ни", tr: "Нартай" },
  { w: "Cloud", c: "Weather and Nature", ipa: "/klaʊd/", mn: "клауд", tr: "Үүл" },
  { w: "Cloudy", c: "Weather and Nature", ipa: "/ˈklaʊdi/", mn: "кла́уди", tr: "Үүлэрхэг" },
  { w: "Rain", c: "Weather and Nature", ipa: "/reɪn/", mn: "рэйн", tr: "Бороо" },
  { w: "Rainy", c: "Weather and Nature", ipa: "/ˈreɪni/", mn: "рэ́йни", tr: "Бороотой" },
  { w: "Snowy", c: "Weather and Nature", ipa: "/ˈsnoʊi/", mn: "сно́уи", tr: "Цастай" },
  { w: "Ice", c: "Weather and Nature", ipa: "/aɪs/", mn: "айс", tr: "Мөс" },
  { w: "Nature", c: "Weather and Nature", ipa: "/ˈneɪtʃər/", mn: "нэ́йчэр", tr: "Байгаль" },
  { w: "Sun", c: "Weather and Nature", ipa: "/sʌn/", mn: "сан", tr: "Нар" },
  { w: "Moon", c: "Weather and Nature", ipa: "/muːn/", mn: "мүүн", tr: "Сар" },
  { w: "Earth", c: "Weather and Nature", ipa: "/ɜːrθ/", mn: "өөрс", tr: "Дэлхий" },
  { w: "Sky", c: "Weather and Nature", ipa: "/skaɪ/", mn: "скай", tr: "Тэнгэр" },
  { w: "River", c: "Weather and Nature", ipa: "/ˈrɪvər/", mn: "ри́вэр", tr: "Гол мөрөн" },
  { w: "Sea", c: "Weather and Nature", ipa: "/siː/", mn: "сий", tr: "Тэнгис, далай" },
  { w: "Mountain", c: "Weather and Nature", ipa: "/ˈmaʊntən/", mn: "ма́унтэн", tr: "Уул" },
  { w: "Beach", c: "Weather and Nature", ipa: "/biːtʃ/", mn: "бийч", tr: "Далайн эрэг" },
  { w: "Forest", c: "Weather and Nature", ipa: "/ˈfɔːrɪst/", mn: "фо́рист", tr: "Ой мод" },
  { w: "Island", c: "Weather and Nature", ipa: "/ˈaɪlənd/", mn: "а́йлэнд", tr: "Арал" },
  { w: "Star", c: "Weather and Nature", ipa: "/stɑːr/", mn: "стаар", tr: "Од" },
  { w: "Tree", c: "Weather and Nature", ipa: "/triː/", mn: "трий", tr: "Мод" },
  { w: "Flower", c: "Weather and Nature", ipa: "/ˈflaʊər/", mn: "фла́уэр", tr: "Цэцэг" },

  // 23. Useful Verbs
  { w: "Hear", c: "Useful Verbs", ipa: "/hɪr/", mn: "хир", tr: "Сонсох" },
  { w: "Listen", c: "Useful Verbs", ipa: "/ˈlɪsən/", mn: "ли́сн", tr: "Чагнах, сонсох" },
  { w: "See", c: "Useful Verbs", ipa: "/siː/", mn: "сий", tr: "Харах" },
  { w: "Look", c: "Useful Verbs", ipa: "/lʊk/", mn: "лүк", tr: "Харах, ширтэх" },
  { w: "Watch", c: "Useful Verbs", ipa: "/wɑːtʃ/", mn: "ваач", tr: "Үзэх, ажиглах" },
  { w: "Touch", c: "Useful Verbs", ipa: "/tʌtʃ/", mn: "тач", tr: "Хүрэх" },
  { w: "Feel", c: "Useful Verbs", ipa: "/fiːl/", mn: "фийл", tr: "Мэдрэх" },
  { w: "Talk", c: "Useful Verbs", ipa: "/tɔːk/", mn: "тоок", tr: "Ярилцах" },
  { w: "Call", c: "Useful Verbs", ipa: "/kɔːl/", mn: "коол", tr: "Залгах" },
  { w: "Like", c: "Useful Verbs", ipa: "/laɪk/", mn: "лайк", tr: "Дуртай байх" },
  { w: "Love", c: "Useful Verbs", ipa: "/lʌv/", mn: "лав", tr: "Хайрлах" },
  { w: "Hate", c: "Useful Verbs", ipa: "/heɪt/", mn: "хэйт", tr: "Үзэн ядах" },
  { w: "Know", c: "Useful Verbs", ipa: "/noʊ/", mn: "ноу", tr: "Мэдэх" },
  { w: "Learn", c: "Useful Verbs", ipa: "/lɜːrn/", mn: "лөөрн", tr: "Сурах" },
  { w: "Ask", c: "Useful Verbs", ipa: "/æsk/", mn: "эск", tr: "Асуух, гуйх" },
  { w: "Study", c: "Useful Verbs", ipa: "/ˈstʌdi/", mn: "ста́ди", tr: "Судлах, хичээл хийх" },
  { w: "Teach", c: "Useful Verbs", ipa: "/tiːtʃ/", mn: "тийч", tr: "Заах" },
  { w: "Need", c: "Useful Verbs", ipa: "/niːd/", mn: "нийд", tr: "Хэрэгцээтэй байх" },
  { w: "Want", c: "Useful Verbs", ipa: "/wɑːnt/", mn: "ваант", tr: "Хүсэх" },
  { w: "Share", c: "Useful Verbs", ipa: "/ʃɛr/", mn: "шээр", tr: "Хуваалцах" },
  { w: "Put", c: "Useful Verbs", ipa: "/pʊt/", mn: "пүт", tr: "Тавих" },
  { w: "Prepare", c: "Useful Verbs", ipa: "/prɪˈpɛr/", mn: "припэ́эр", tr: "Бэлтгэх" },
  { w: "Plan", c: "Useful Verbs", ipa: "/plæn/", mn: "плэн", tr: "Төлөвлөх" },
  { w: "Explain", c: "Useful Verbs", ipa: "/ɪkˈspleɪn/", mn: "эксплэ́йн", tr: "Тайлбарлах" },
  { w: "Fill", c: "Useful Verbs", ipa: "/fɪl/", mn: "фил", tr: "Дүүргэх" },
  { w: "Fly", c: "Useful Verbs", ipa: "/flaɪ/", mn: "флай", tr: "Нисэх" },
  { w: "Get", c: "Useful Verbs", ipa: "/ɡɛt/", mn: "гэт", tr: "Авах, болох" },
  { w: "Become", c: "Useful Verbs", ipa: "/bɪˈkʌm/", mn: "бика́м", tr: "Болох, хувирах" },

  // 24. School
  { w: "School", c: "School", ipa: "/skuːl/", mn: "скүүл", tr: "Сургууль" },
  { w: "College", c: "School", ipa: "/ˈkɑːlɪdʒ/", mn: "ка́лиж", tr: "Коллеж" },
  { w: "University", c: "School", ipa: "/ˌjuːnɪˈvɜːrsəti/", mn: "юнивөө́рсити", tr: "Их сургууль" },
  { w: "Preschool", c: "School", ipa: "/ˈpriːskuːl/", mn: "при́йскүүл", tr: "Цэцэрлэг" },
  { w: "Classroom", c: "School", ipa: "/ˈklæsruːm/", mn: "клэ́срүүм", tr: "Анги танхим" },
  { w: "Student", c: "School", ipa: "/ˈstuːdənt/", mn: "стүү́дэнт", tr: "Сурагч, оюутан" },
  { w: "Book", c: "School", ipa: "/bʊk/", mn: "бүк", tr: "Ном" },
  { w: "Notebook", c: "School", ipa: "/ˈnoʊtbʊk/", mn: "но́утбүк", tr: "Дэвтэр" },
  { w: "Bag", c: "School", ipa: "/bæɡ/", mn: "бэг", tr: "Цүнх" },
  { w: "Pen", c: "School", ipa: "/pɛn/", mn: "пэн", tr: "Үзэг" },
  { w: "Pencil", c: "School", ipa: "/ˈpɛnsəl/", mn: "пэ́нсл", tr: "Харандаа" },
  { w: "Eraser", c: "School", ipa: "/ɪˈreɪsər/", mn: "ирэ́йсэр", tr: "Баллуур" },
  { w: "Marker", c: "School", ipa: "/ˈmɑːrkər/", mn: "ма́аркэр", tr: "Тодруулагч" },
  { w: "Homework", c: "School", ipa: "/ˈhoʊmwɜːrk/", mn: "хо́умвөөөрк", tr: "Гэрийн даалгавар" },
  { w: "History", c: "School", ipa: "/ˈhɪstəri/", mn: "хи́стэри", tr: "Түүх" },
  { w: "Language", c: "School", ipa: "/ˈlæŋɡwɪdʒ/", mn: "лэ́нгвиж", tr: "Хэл" },
  { w: "Science", c: "School", ipa: "/ˈsaɪəns/", mn: "са́йэнс", tr: "Шинжлэх ухаан" },
  { w: "Class", c: "School", ipa: "/klæs/", mn: "клэс", tr: "Хичээл, анги" },

  // 25. City
  { w: "City", c: "City", ipa: "/ˈsɪti/", mn: "си́ти", tr: "Хот" },
  { w: "Town", c: "City", ipa: "/taʊn/", mn: "таун", tr: "Жижиг хот" },
  { w: "Street", c: "City", ipa: "/striːt/", mn: "стрийт", tr: "Гудамж" },
  { w: "Bank", c: "City", ipa: "/bæŋk/", mn: "бэнк", tr: "Банк" },
  { w: "Hospital", c: "City", ipa: "/ˈhɑːspɪtəl/", mn: "ха́спитл", tr: "Эмнэлэг" },
  { w: "Restaurant", c: "City", ipa: "/ˈrɛstərənt/", mn: "рэ́стэрант", tr: "Ресторан" },
  { w: "Movie theater", c: "City", ipa: "/ˈmuːvi ˌθiːətər/", mn: "мүү́ви си́йтэр", tr: "Кино театр" },
  { w: "Supermarket", c: "City", ipa: "/ˈsuːpərmɑːrkɪt/", mn: "сүү́пэрмааркит", tr: "Супермаркет" },
  { w: "Post office", c: "City", ipa: "/ˈpoʊst ˌɔːfɪs/", mn: "по́уст о́фис", tr: "Шуудан" },
  { w: "Bench", c: "City", ipa: "/bɛntʃ/", mn: "бэнч", tr: "Сандал (цэцэрлэгийн)" },
  { w: "Museum", c: "City", ipa: "/mjuːˈziːəm/", mn: "мьюзи́йэм", tr: "Музей" },
  { w: "Park", c: "City", ipa: "/pɑːrk/", mn: "паарк", tr: "Парк" },
  { w: "Hotel", c: "City", ipa: "/hoʊˈtɛl/", mn: "хоутэ́л", tr: "Зочид буудал" },
  { w: "Police", c: "City", ipa: "/pəˈliːs/", mn: "пэли́йс", tr: "Цагдаа" },
  { w: "Map", c: "City", ipa: "/mæp/", mn: "мэп", tr: "Газрын зураг" },

  // 26. Free Time Activities
  { w: "Hobby", c: "Free Time", ipa: "/ˈhɑːbi/", mn: "ха́би", tr: "Хобби" },
  { w: "Movie", c: "Free Time", ipa: "/ˈmuːvi/", mn: "мүү́ви", tr: "Кино" },
  { w: "Music", c: "Free Time", ipa: "/ˈmjuːzɪk/", mn: "мью́зик", tr: "Хөгжим" },
  { w: "Guitar", c: "Free Time", ipa: "/ɡɪˈtɑːr/", mn: "гита́ар", tr: "Гитар" },
  { w: "Piano", c: "Free Time", ipa: "/piˈænoʊ/", mn: "пиэ́ноу", tr: "Төгөлдөр хуур" },
  { w: "Violin", c: "Free Time", ipa: "/ˌvaɪəˈlɪn/", mn: "вайэли́н", tr: "Хийл" },
  { w: "Swimming", c: "Free Time", ipa: "/ˈswɪmɪŋ/", mn: "сви́мин", tr: "Усанд сэлэлт" },
  { w: "Soccer", c: "Free Time", ipa: "/ˈsɑːkər/", mn: "са́кэр", tr: "Хөлбөмбөг" },
  { w: "Volleyball", c: "Free Time", ipa: "/ˈvɑːlibɔːl/", mn: "ва́либоол", tr: "Гар бөмбөг" },
  { w: "Hiking", c: "Free Time", ipa: "/ˈhaɪkɪŋ/", mn: "ха́йкин", tr: "Ууланд алхалт" },
  { w: "Tennis", c: "Free Time", ipa: "/ˈtɛnɪs/", mn: "тэ́нис", tr: "Теннис" },
  { w: "Bicycle", c: "Free Time", ipa: "/ˈbaɪsɪkəl/", mn: "ба́йсикл", tr: "Унадаг дугуй" },
  { w: "Sport", c: "Free Time", ipa: "/spɔːrt/", mn: "споорт", tr: "Спорт" },
  { w: "Game", c: "Free Time", ipa: "/ɡeɪm/", mn: "гэйм", tr: "Тоглоом" },
  { w: "Video game", c: "Free Time", ipa: "/ˈvɪdioʊ ɡeɪm/", mn: "ви́диоу гэйм", tr: "Видео тоглоом" },
  { w: "Newspaper", c: "Free Time", ipa: "/ˈnuːzpeɪpər/", mn: "нүү́зпэйпэр", tr: "Сонин" },
  { w: "Magazine", c: "Free Time", ipa: "/ˌmæɡəˈziːn/", mn: "мэгэзи́йн", tr: "Сэтгүүл" },

  // 27. Countries and Nationalities
  { w: "Country", c: "Countries", ipa: "/ˈkʌntri/", mn: "ка́нтри", tr: "Улс орон" },
  { w: "United States", c: "Countries", ipa: "/juːˌnaɪtɪd ˈsteɪts/", mn: "юна́йтид стэ́йтс", tr: "АНУ" },
  { w: "American", c: "Countries", ipa: "/əˈmɛrɪkən/", mn: "эмэ́рикэн", tr: "Америк" },
  { w: "Canada", c: "Countries", ipa: "/ˈkænədə/", mn: "кэ́нэдэ", tr: "Канад" },
  { w: "Canadian", c: "Countries", ipa: "/kəˈneɪdiən/", mn: "кэнэ́йдиэн", tr: "Канад хүн" },
  { w: "United Kingdom", c: "Countries", ipa: "/juːˌnaɪtɪd ˈkɪŋdəm/", mn: "юна́йтид ки́нгдэм", tr: "Их Британи" },
  { w: "British", c: "Countries", ipa: "/ˈbrɪtɪʃ/", mn: "бри́тиш", tr: "Британи" },
  { w: "Germany", c: "Countries", ipa: "/ˈdʒɜːrməni/", mn: "жөө́рмэни", tr: "Герман" },
  { w: "German", c: "Countries", ipa: "/ˈdʒɜːrmən/", mn: "жөө́рмэн", tr: "Герман хүн" },
  { w: "France", c: "Countries", ipa: "/fræns/", mn: "фрэнс", tr: "Франц" },
  { w: "French", c: "Countries", ipa: "/frɛntʃ/", mn: "фрэнч", tr: "Франц хүн" },
  { w: "Spain", c: "Countries", ipa: "/speɪn/", mn: "спэйн", tr: "Испани" },
  { w: "Spanish", c: "Countries", ipa: "/ˈspænɪʃ/", mn: "спэ́ниш", tr: "Испани хүн" },
  { w: "Italy", c: "Countries", ipa: "/ˈɪtəli/", mn: "и́тэли", tr: "Итали" },
  { w: "Italian", c: "Countries", ipa: "/ɪˈtæljən/", mn: "итэ́льен", tr: "Итали хүн" },

  // 28. Simple Verbs
  { w: "Walk", c: "Simple Verbs", ipa: "/wɔːk/", mn: "воок", tr: "Алхах" },
  { w: "Run", c: "Simple Verbs", ipa: "/rʌn/", mn: "ран", tr: "Гүйх" },
  { w: "Go", c: "Simple Verbs", ipa: "/ɡoʊ/", mn: "гоу", tr: "Явах" },
  { w: "Come", c: "Simple Verbs", ipa: "/kʌm/", mn: "кам", tr: "Ирэх" },
  { w: "Sit", c: "Simple Verbs", ipa: "/sɪt/", mn: "сит", tr: "Суух" },
  { w: "Fall", c: "Simple Verbs", ipa: "/fɔːl/", mn: "фоол", tr: "Унах" },
  { w: "Jump", c: "Simple Verbs", ipa: "/dʒʌmp/", mn: "жамп", tr: "Үсрэх" },
  { w: "Bring", c: "Simple Verbs", ipa: "/brɪŋ/", mn: "брин", tr: "Авчрах" },
  { w: "Give", c: "Simple Verbs", ipa: "/ɡɪv/", mn: "гив", tr: "Өгөх" },
  { w: "Find", c: "Simple Verbs", ipa: "/faɪnd/", mn: "файнд", tr: "Олох" },
  { w: "Open", c: "Simple Verbs", ipa: "/ˈoʊpən/", mn: "о́упэн", tr: "Нээх" },
  { w: "Close", c: "Simple Verbs", ipa: "/kloʊz/", mn: "клоуз", tr: "Хаах" },
  { w: "Start", c: "Simple Verbs", ipa: "/stɑːrt/", mn: "стаарт", tr: "Эхлэх" },
  { w: "Stop", c: "Simple Verbs", ipa: "/stɑːp/", mn: "стаап", tr: "Зогсох" },
  { w: "Finish", c: "Simple Verbs", ipa: "/ˈfɪnɪʃ/", mn: "фи́ниш", tr: "Дуусгах" },
  { w: "Build", c: "Simple Verbs", ipa: "/bɪld/", mn: "билд", tr: "Барих" },
  { w: "Do", c: "Simple Verbs", ipa: "/duː/", mn: "дүү", tr: "Хийх" },
  { w: "Turn", c: "Simple Verbs", ipa: "/tɜːrn/", mn: "төөөрн", tr: "Эргэх" },
  { w: "Introduce", c: "Simple Verbs", ipa: "/ˌɪntrəˈduːs/", mn: "интрэдүү́с", tr: "Танилцуулах" },
  { w: "Travel", c: "Simple Verbs", ipa: "/ˈtrævəl/", mn: "трэ́вл", tr: "Аялах" },
  { w: "Let", c: "Simple Verbs", ipa: "/lɛt/", mn: "лэт", tr: "Зөвшөөрөх" },
  { w: "Choose", c: "Simple Verbs", ipa: "/tʃuːz/", mn: "чүүз", tr: "Сонгох" },
  { w: "Help", c: "Simple Verbs", ipa: "/hɛlp/", mn: "хэлп", tr: "Туслах" },
  { w: "Swim", c: "Simple Verbs", ipa: "/swɪm/", mn: "свим", tr: "Сэлэх" },

  // 29. Transportation
  { w: "Car", c: "Transportation", ipa: "/kɑːr/", mn: "каар", tr: "Машин" },
  { w: "Motorcycle", c: "Transportation", ipa: "/ˈmoʊtərˌsaɪkəl/", mn: "мо́утэрсайкл", tr: "Мотоцикл" },
  { w: "Bus", c: "Transportation", ipa: "/bʌs/", mn: "бас", tr: "Автобус" },
  { w: "Truck", c: "Transportation", ipa: "/trʌk/", mn: "трак", tr: "Ачааны машин" },
  { w: "Train", c: "Transportation", ipa: "/treɪn/", mn: "трэйн", tr: "Галт тэрэг" },
  { w: "Taxi", c: "Transportation", ipa: "/ˈtæksi/", mn: "тэ́кси", tr: "Такси" },
  { w: "Subway", c: "Transportation", ipa: "/ˈsʌbweɪ/", mn: "са́бвэй", tr: "Метро" },
  { w: "Airplane", c: "Transportation", ipa: "/ˈɛrpleɪn/", mn: "э́эрплэйн", tr: "Онгоц" },
  { w: "Helicopter", c: "Transportation", ipa: "/ˈhɛlɪˌkɑːptər/", mn: "хэ́ликоптэр", tr: "Нисдэг тэрэг" },
  { w: "Ship", c: "Transportation", ipa: "/ʃɪp/", mn: "шип", tr: "Усан онгоц" },
  { w: "Boat", c: "Transportation", ipa: "/boʊt/", mn: "боут", tr: "Завь" },
  { w: "Ticket", c: "Transportation", ipa: "/ˈtɪkɪt/", mn: "ти́кит", tr: "Тасалбар" },
  { w: "Van", c: "Transportation", ipa: "/væn/", mn: "вэн", tr: "Фургон, микро" },
  { w: "Station", c: "Transportation", ipa: "/ˈsteɪʃən/", mn: "стэ́йшн", tr: "Буудал" },
  { w: "Airport", c: "Transportation", ipa: "/ˈɛrpɔːrt/", mn: "э́эрпоорт", tr: "Нисэх буудал" },
  { w: "Train station", c: "Transportation", ipa: "/treɪn ˈsteɪʃən/", mn: "трэ́йн стэйшн", tr: "Галт тэрэгний буудал" },

  // 30. Directions and Continents
  { w: "Place", c: "Directions", ipa: "/pleɪs/", mn: "плэйс", tr: "Газар, байршил" },
  { w: "North", c: "Directions", ipa: "/nɔːrθ/", mn: "ноорс", tr: "Хойд зүг" },
  { w: "South", c: "Directions", ipa: "/saʊθ/", mn: "саус", tr: "Өмнөд зүг" },
  { w: "East", c: "Directions", ipa: "/iːst/", mn: "йийст", tr: "Зүүн зүг" },
  { w: "West", c: "Directions", ipa: "/wɛst/", mn: "вэст", tr: "Баруун зүг" },
  { w: "Back", c: "Directions", ipa: "/bæk/", mn: "бэк", tr: "Ар тал, буцаад" },
  { w: "Right", c: "Directions", ipa: "/raɪt/", mn: "райт", tr: "Баруун тийш" },
  { w: "Left", c: "Directions", ipa: "/lɛft/", mn: "лэфт", tr: "Зүүн тийш" },
  { w: "Far", c: "Directions", ipa: "/fɑːr/", mn: "фаар", tr: "Хол" },
  { w: "Continent", c: "Directions", ipa: "/ˈkɑːntɪnənt/", mn: "ка́нтинэнт", tr: "Тив" },
  { w: "Asia", c: "Directions", ipa: "/ˈeɪʒə/", mn: "э́йжа", tr: "Ази тив" },
  { w: "Asian", c: "Directions", ipa: "/ˈeɪʒən/", mn: "э́йжан", tr: "Азийн" },
  { w: "Europe", c: "Directions", ipa: "/ˈjʊrəp/", mn: "ю́рэп", tr: "Европ тив" },
  { w: "European", c: "Directions", ipa: "/ˌjʊrəˈpiːən/", mn: "юрэпи́йэн", tr: "Европын" },
  { w: "Africa", c: "Directions", ipa: "/ˈæfrɪkə/", mn: "э́фрикэ", tr: "Африк тив" },
  { w: "African", c: "Directions", ipa: "/ˈæfrɪkən/", mn: "э́фрикэн", tr: "Африкийн" },

  // 31. Adverbs and Pronouns
  { w: "Outside", c: "Adverbs and Pronouns", ipa: "/ˌaʊtˈsaɪd/", mn: "аутса́йд", tr: "Гадаа" },
  { w: "Always", c: "Adverbs and Pronouns", ipa: "/ˈɔːlweɪz/", mn: "о́олвэйз", tr: "Үргэлж" },
  { w: "Never", c: "Adverbs and Pronouns", ipa: "/ˈnɛvər/", mn: "нэ́вэр", tr: "Хэзээ ч үгүй" },
  { w: "Usually", c: "Adverbs and Pronouns", ipa: "/ˈjuːʒuəli/", mn: "ю́үжүэли", tr: "Ихэвчлэн" },
  { w: "Often", c: "Adverbs and Pronouns", ipa: "/ˈɔːfən/", mn: "о́офэн", tr: "Олонтоо, байнга" },
  { w: "Sometimes", c: "Adverbs and Pronouns", ipa: "/ˈsʌmˌtaɪmz/", mn: "са́мтаймз", tr: "Заримдаа" },
  { w: "Now", c: "Adverbs and Pronouns", ipa: "/naʊ/", mn: "нау", tr: "Одоо" },
  { w: "Soon", c: "Adverbs and Pronouns", ipa: "/suːn/", mn: "сүүн", tr: "Удахгүй" },
  { w: "Too", c: "Adverbs and Pronouns", ipa: "/tuː/", mn: "түү", tr: "Бас, хэтэрхий" },
  { w: "Here", c: "Adverbs and Pronouns", ipa: "/hɪr/", mn: "хир", tr: "Энд" },
  { w: "There", c: "Adverbs and Pronouns", ipa: "/ðɛr/", mn: "дээр", tr: "Тэнд" },
  { w: "Again", c: "Adverbs and Pronouns", ipa: "/əˈɡɛn/", mn: "эгэ́н", tr: "Дахин" },
  { w: "Of course", c: "Adverbs and Pronouns", ipa: "/əv kɔːrs/", mn: "эв коорс", tr: "Мэдээж" },
  { w: "Really", c: "Adverbs and Pronouns", ipa: "/ˈriːəli/", mn: "ри́йэли", tr: "Үнэхээр" },
  { w: "Why", c: "Adverbs and Pronouns", ipa: "/waɪ/", mn: "вай", tr: "Яагаад" },
  { w: "Where", c: "Adverbs and Pronouns", ipa: "/wɛr/", mn: "вээр", tr: "Хаана" },
  { w: "When", c: "Adverbs and Pronouns", ipa: "/wɛn/", mn: "вэн", tr: "Хэзээ" },
  { w: "What", c: "Adverbs and Pronouns", ipa: "/wɑːt/", mn: "ваат", tr: "Юу" },
  { w: "Who", c: "Adverbs and Pronouns", ipa: "/huː/", mn: "хүү", tr: "Хэн" },
  { w: "How", c: "Adverbs and Pronouns", ipa: "/haʊ/", mn: "хау", tr: "Яаж, хэрхэн" },
  { w: "Else", c: "Adverbs and Pronouns", ipa: "/ɛls/", mn: "элс", tr: "Өөр" },

  // 32. Prepositions and Determiners
  { w: "Before", c: "Prepositions", ipa: "/bɪˈfɔːr/", mn: "бифо́ор", tr: "Өмнө" },
  { w: "After", c: "Prepositions", ipa: "/ˈæftər/", mn: "э́фтэр", tr: "Дараа" },
  { w: "At", c: "Prepositions", ipa: "/æt/", mn: "эт", tr: "-д, -т (цаг, газар)" },
  { w: "In", c: "Prepositions", ipa: "/ɪn/", mn: "ин", tr: "Дотор, -д, -т" },
  { w: "On", c: "Prepositions", ipa: "/ɑːn/", mn: "аан", tr: "Дээр" },
  { w: "Below", c: "Prepositions", ipa: "/bɪˈloʊ/", mn: "било́у", tr: "Доогуур" },
  { w: "Above", c: "Prepositions", ipa: "/əˈbʌv/", mn: "эба́в", tr: "Дээгүүр" },
  { w: "Across", c: "Prepositions", ipa: "/əˈkrɔːs/", mn: "экро́ос", tr: "Хөндлөн" },
  { w: "Near", c: "Prepositions", ipa: "/nɪr/", mn: "нир", tr: "Ойрхон" },
  { w: "Between", c: "Prepositions", ipa: "/bɪˈtwiːn/", mn: "битви́йн", tr: "Хооронд" },
  { w: "Next to", c: "Prepositions", ipa: "/nɛkst tuː/", mn: "нэкст түү", tr: "Хажууд" },
  { w: "Behind", c: "Prepositions", ipa: "/bɪˈhaɪnd/", mn: "биха́йнд", tr: "Ард" },
  { w: "With", c: "Prepositions", ipa: "/wɪð/", mn: "виз", tr: "-тай хамт" },
  { w: "To", c: "Prepositions", ipa: "/tuː/", mn: "түү", tr: "Тийшээ, руу" },
  { w: "Another", c: "Prepositions", ipa: "/əˈnʌðər/", mn: "эна́дэр", tr: "Өөр нэг" },
  { w: "This", c: "Prepositions", ipa: "/ðɪs/", mn: "дис", tr: "Энэ" },
  { w: "That", c: "Prepositions", ipa: "/ðæt/", mn: "дэт", tr: "Тэр" },
  { w: "Both", c: "Prepositions", ipa: "/boʊθ/", mn: "боус", tr: "Хоёулаа" },
  { w: "A", c: "Prepositions", ipa: "/ə/", mn: "э", tr: "Нэгэн (тодорхойгүй)" },
  { w: "Over", c: "Prepositions", ipa: "/ˈoʊvər/", mn: "о́увэр", tr: "Дээгүүр" },
  { w: "Under", c: "Prepositions", ipa: "/ˈʌndər/", mn: "а́ндэр", tr: "Доор" }
];